version: '3.8'
services:
  order-service:
    build: ./Pedidos
    env_file:
      - ../.env
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=3003
      - DATABASE_SERVICE_URL=http://database-service:3003
    ports:
      - "${ORDERS_PORT}:3003"
    depends_on:
      - db
      - database-service
    networks:
      - dev-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${ORDERS_MYSQL_PORT}:3303"
    volumes:
      - orders_db_data:/var/lib/mysql
    networks:
      - dev-network

  database-service:
    build:
      context: ./Database
      dockerfile: dockerfile
    env_file:
      - ../.env
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=3003
    depends_on:
      - db
    networks:
      - dev-network
    ports:
      - "${ORDERS_DATABASE_PORT}:4003"

volumes:
  orders_db_data:

networks:
  dev-network:
    driver: bridge
